<a href="https://colab.research.google.com/github/HyungJunByun/practice-history/blob/main/%ED%86%B5%EA%B3%84%ED%95%99%EC%8B%A4%ED%97%98_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

예제 1. 1부터 100 사이에서 40개의 서로 다른 정수를 임의로 선택하여 저장하자

In [1]:
import numpy as np
x=np.random.randint(1,101,40)

In [3]:
#1-1) 만들어진 벡터를 사용하여 5행 8열의 행렬을 생성하시오
x=x.reshape(5,8)
print(x)

[[ 78  84   6  77  40  36  58  14]
 [ 84  55  80   4  19  12  61  58]
 [ 74  77  20  35  59  21  72  77]
 [ 84  18  11  41  31  48  76 100]
 [  2  79  20  74  22  85  49  21]]


In [4]:
#1-2) 예제 1에서 생성된 행렬에서 2행과 3행만을 추출하여 저장하시오
x2=x[1:3]
print(x2)

[[84 55 80  4 19 12 61 58]
 [74 77 20 35 59 21 72 77]]


In [5]:
#1-3) 예제 1에서 생성된 행렬에서 (1,4,7,8)열을 추출하여 저장하시오
x3=x[:,[0,3,6,7]]
print(x3)

[[ 78  77  58  14]
 [ 84   4  61  58]
 [ 74  35  72  77]
 [ 84  41  76 100]
 [  2  74  49  21]]


In [7]:
#1-4) 예제 1에서 생성된 행렬의 7번째 열의 평균과 분산을 구하시오.
print(x[:,6].mean())
print(x[:,6].var())

63.2
94.96


예제2. 1부터 20 사이에서 1개의 숫자를 임의로 선택하여 저장하자. 이 숫자가 10이상이면 "P"를 출력하고 10 미만이면 "NP"를 출력하는 코드를 작성해보시오.

In [12]:
num=np.random.randint(1,21)
print("random number: %d" %num)
if num>=10:
  print("P")
else:
  print("NP")

random number: 14
P


예제3. 1부터 20 사이에서 8개의 숫자를 임의로 선택하여 저장하자. 8개의 숫자들 각각에 대해 숫자가 10이상이면 "P"를 출력하고 10미만이면 "NP"를 출력하는 코드를 작성해보시오.

In [13]:
numlist=np.random.randint(1,21,8)
for num in numlist:
  if num>=10:
    print("P")
  else:
    print("NP")

P
NP
NP
NP
P
P
P
NP
